= test
:author: David Buret
:source-highlighter: pygments
:pygments-style: emacs
:icons: font
:sectnums:
:toclevels: 4
:toc:
:imagesdir: images/
:toc-title: Sommaire

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++
 
[descrete]
== Controle du document

blah blah

kbd:[Ctrl + 1]

// comment

== texte

forced + line break 


normal, _italic_, *bold*, +mono+. 
``double quoted'', `single quoted'. 


"Double cité", "unique cité".

normal, super , sous .

Command: `ls -al` 
+mono *bold*+ 
`passthru *bold*` 
Commande: ls -al



Path: '/some/filez.txt', '.b' 


[red]#red text# [yellow-background]#on yellow# 
[big]#large# [red yellow-background big]
*all bold* 


Chars: n__i__**b**++m++[red]##r## 


// Comment 
(C) (R) (TM) -- ... -> <- => <= &#182; 
© ® ™ - ... → ← ⇒ ⇐ ¶

'''' 
Escaped: 
\_italic_, +++_italic_+++, 
t\__e__st, +++t__e__st+++, 
+++<b>bold</b>+++, $$<b>normal</b>$$ 
\&#182; 
\`not single quoted' 
\`\`not double quoted'' 

== blocs

=== literal

.optional title
----
bloc literal
----

=== sidebar

.Optional Title 
**** 
*Sidebar* Block 
Use: sidebar notes :) 
**** 

=== exemple

.Optional Title 
========================== 
*Example* Block 
Use: examples :) 
Default caption "Example:" can be changed using 
[caption="Custom: "] 
before example block. 
========================== 

=== quote

.Optional Title 
[quote, cite author, cite source] 
____ 
*Quote* Block 
Use: cite somebody 
____ 

=== amonition 

----
Type: paragraph 
----

.types
- NOTE
- TIP
- WARNING
- CAUTION
- IMPORTANT

WARNING: TEST

== generate zdoc file with all'includes included

https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb

allow HTTP includes:pass the -a allow-uri-read flag to the script:

[source,sh]
----
$ ruby adoc.rb mydoc.adoc -a allow-uri-read 
----

== Code

[source,go,linenums]
----
func main() {
	var programVersion = "0.4"
	var programName = "gse"

	var uri string
	var port string

	uri, port = pathandport.Parse(programName, "28657") # <1>

	mux := http.NewServeMux()
	mux.HandleFunc(uri, handler)
	s := &http.Server{
		Addr:    fmt.Sprintf(":%s", port),
		Handler: mux,
	}

	log.Printf("Starting %s (%s) on port %s with basepath %s ...\n", programName, programVersion, port, uri)
	log.Fatal(s.ListenAndServe()) # <2>
}
----
<1> commentaire 1
<2> commentaire 2

== listes

=== par defaut

.Type de mémoire
RAM:: Random Access Memory
ROM:: Read Only Memory
NVRAM:: Non volatile random access memory

=== horizontale

[horizontal]
.Type de mémoire
RAM:: Random Access Memory
ROM:: Read Only Memory
NVRAM:: Non volatile random access memory


== checklist


. Tâches à faire
- [*] Tache 1
- [x] Tache 2
- [ ] Tache 3
- [ ] Tache 4

== tables

le tableau, ou tout ou partie de son contenu peuvent être dans un  fichier séparé 

----
\include::fichier[commentaire]
----

ou servi par un serveur web (et doc pourrait aussi bien etre le resultat d'une query)

----
\include::url[commentaire]
----

.CSV data, 15% each column 
[format="csv",width="60%",cols="4"] 
[frame="topbot",grid="none"] 
|====== 
1,2,3,4 
a,b,c,d 
A,B,C,D 
|====== 

.alignement dans les fellules
[grid="rows",format="csv"] 
[options="header",cols="^,<,<s,<,>m"] 
|=========================== 
ID,FName,LName,Address,Phone 
1,Vasya,Pupkin,London,+123 
2,X,Y,"A,B",45678 
|=========================== 



.Multiline cells, row/col span 
|==== 
|Date |Duration |Avg HR |Notes 
|22-Aug-08 .2+^.^|10:24 | 157 | 
Worked out MSHR (max sustainable 
heart rate) by going hard 
for this interval. 

|22-Aug-08 | 152 | 
Back-to-back with previous interval. 

|24-Aug-08 3+^|none 

|==== 

== images 

----
image::fileOrURL[width=100%, scalewidth=17cm]
----

== plantUML

=== embedded 

[source,plantuml]
----
[plantuml]
\----
node webapp{
	[webapp.fo.rest]	 
}

node intf_fo{
	[intf.fo]
}
 
node impl{
	[impl.fo]
	[impl.biz]
}
[impl.fo] -down-> [impl.biz]

[webapp.fo.rest] -down-> [intf.fo]
[impl.fo] .up.> [intf.fo] : implements
\----
----

=== external file
plantuml::test.puml[plantuml,png]

=== url

plantuml::https://raw.githubusercontent.com/DBuret/myjournal/master/test.pumll[plantuml,png]

=== url that generates image

need plantuml server
[source]
----
image::http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/DBuret/myjournal/master/test.puml[test]
----

syntax is very long, let'use an asciidoc variable +gitplant+ giving location of server + puml file

.how to display plantuml in asciidoc on github
[source]
----
:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/DBuret/myjournal/master/

image::{gitplant}/test.puml[test]
----

note that src could be a web service generating puml on the fly from a use case stored in a db.


== macro

https://markhneedham.com/blog/2018/02/19/asciidoctor-creating-macro/

== syntax highlighting 

=== pygments styles

https://help.farbox.com/pygments.html


