@startuml
 

cloud internet {
   actor user 
}

node fw 

user -d-> fw: https
Rectangle IS {

Rectangle dmzFront {
Node externalRP
}

fw -d-> externalRP: https

Rectangle dmzInternet {
Cloud IdraaInternet {
   component traefikselidi
component traefikselida

   Component FrontAuthda
Component FrontAuthdi
   Component FrontStatiquedi
Component FrontStatiqueda
}
}

externalRP .d.> traefikselidi: http

externalRP .d.> traefikselida: http

traefikselidi .d.> FrontStatiquedi
traefikselidi .d.> FrontAuthdi

traefikselida .d.> FrontStatiqueda
traefikselida .d.> FrontAuthda

Rectangle dmzProd {
Component internalRP

FrontAuthdi .d.> internalRP

FrontAuthda .d.> internalRP


Cloud idraa-prod {
Component traefikdi
Component Backenddi
Component traefikda
Component Backendda
}

Database mysql
}

 internalRP .d.> traefikdi

internalRP .d.> traefikda

traefikdi .d.> Backenddi
traefikda .d.> Backendda


Backendda .d.> mysql
Backenddi .d.> mysql


}
@enduml