@startuml
!includeurl  https://raw.githubusercontent.com/DBuret/myjournal/master/plantuml.cfg

 rectangle "<$globe_internet>\n" as internet
 rectangle "<$voip_gateway>\nfreebox" as freebox
 rectangle "<$modem>\nrouteur" as routeur
 rectangle "<$switch>\nswitch\nsalon" as salon
 rectangle "<$switch>\nswitch\nbureau" as bureau
 rectangle "<$switch>\nswitch\nchambre" as chambre
 rectangle "<$wifi>" as wifi
 
 
 rectangle "<$workstation>\nPC" as pc
 rectangle "<$device_laptop>\nalienware" as alien
 rectangle "<$file_server>\nNAS" as nas
 rectangle "<$server_farm>\nsupermicro" as server
 
 rectangle "<$device_tv>\nchambre" as tvch
rectangle "<$chrome>\nchambre" as ccchambre
 
 rectangle "<$device_tv>\nsalon" as tvsalon
 rectangle "<$film>\nfreebox player" as player
 rectangle "<$film>\n<$gamepad>\nshield" as shield
 rectangle "<$music>\nampli denon" as denon 
 rectangle "<$gamepad>\nWiiU" as wiiU
 
 rectangle "<$device_printer>" as print
 
 rectangle "<$chrome>\ncuisine" as cccuisine
 
rectangle "<$cell_phone_generic>\nmanon" as telmanon
rectangle "<$cell_phone_generic>\nsylvain" as telsylvain
rectangle "<$cell_phone_generic>\nelisa" as telelisa
rectangle "<$cell_phone_generic>\ndavid" as teldavid
rectangle "<$cell_phone_generic>\ncorinne" as telcorinne
rectangle "<$device_tablet_ipad>\ndavid" as ipad
rectangle "<$device_tablet_ipad>\ncorinne" as ipadmini
rectangle "<$device_laptop>\nsylvain" as tabsylvain
rectangle "<$device_laptop>\nelisa" as tabelisa
rectangle "<$device_laptop>\nmanon" as lapmanon
 
 
internet -- freebox
freebox -- routeur

routeur = salon <<https>> : "vlan 100\n& untagged"
routeur ---- wifi
routeur -- bureau
routeur -l- chambre

chambre -l- tvch 

bureau -- nas
bureau -- pc
bureau -- alien 
bureau -- server

salon = player  <<https>> : "vlan 100\n& untagged"
salon -- shield
salon -- denon 
salon -- wiiU

wifi -- print 
wifi -- tvsalon
wifi -- cccuisine
wifi -- ccchambre
wifi -- telmanon
wifi -- telsylvain
wifi -- telelisa
wifi -- teldavid
wifi -- telcorinne
wifi -- ipad
wifi -- ipadmini
wifi -- tabsylvain
wifi -- tabelisa
wifi -- lapmanon

@enduml