@startuml
!includeurl  https://raw.githubusercontent.com/DBuret/myjournal/master/plantuml.cfg

 rectangle "<$globe_internet>" as internet
 rectangle "<$voip_gateway>\nfreebox" as freebox
 rectangle "<$modem>\nrouteur" as routeur
 rectangle "<$switch>\nsalon" as salon
 rectangle "<$switch>\nbureau" as bureau
 rectangle "<$switch>\nchambre" as chambre
 rectangle "<$wifi>" as wifi
 
 
 rectangle "<$workstation>\nPC" as pc
 rectangle "<$device_laptop>\nalienware" as alien
 rectangle "<$file_server>\nNAS" as nas
 
 
 rectangle "<$device_tv>\nchambre" as tvch
rectangle "<$chrome>\nchambre" as ccchambre
 
 rectangle "<$device_tv>\nsalon" as tvsalon
 rectangle "<$film>\nfreebox player" as player
 rectangle "<$film>\nshield" as shield
 rectangle "<$music>\nampli denon" as denon 
 rectangle "<$nintendo_switch>\nWiiU" as wiiU
 
 rectangle "<$device_printer>" as print
 
 rectangle "<$chrome>\ncuisine" as cccuisine
 
 
 
internet -- freebox
freebox -- routeur

routeur == salon <<https>>
routeur -- wifi
routeur -- bureau
routeur -- chambre

chambre -- tvch 

bureau -- nas
bureau -- pc
bureau -- alien 

salon == player  <<https>>
salon -- shield
salon -- denon 
salon -- print 
salon -- wiiU
salon -- tvsalon

@enduml