= notes de lecture
:author: David Buret
:source-highlighter: pygments
:pygments-style: emacs
:icons: font
:sectnums:
:toclevels: 4
:toc:
:imagesdir: images/
:toc-title: Sommaire
:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/DBuret/myjournal/master/

== A creuser
 
cette section est in pense bete des sujets a creuser
 
* uml: revenir aux sources, lire la doc officielle de http://www.omg.org
* iso 42010
 

== en cours
 
.Management
* the toyota way (management)
* demming
 
.Architecture
* uml'2.0'in action
* Software Systems Architecture: 
Working with Stakeholders Using Viewpoints and Perspectives (
Nick Rozanski,
Eoin Woods)
* doc as code, arc42 : https://doctoolchain.github.io/docToolchain/
 
== Software Systems Architecture: Working with Stakeholders Using Viewpoints and Perspectives 

.Notes de lectures
* le triangle qualite,cout,time to market est a reutiliser
** l'ameliorer en montrant que methodes et outillage modifient la forme du triangle et pas seuleent notre position dedans

* il faut devenir expert un diagrammes de deploiement, et adapterr le concept au plateformes cloud & conteneurs
* il faut formaliser quels sont mes stakeholders, et definir les viewpoints et perspectives adaptés a notre contexte, puis les repartir entre nos livrables (DA, Narc, ppt caop, ppt cvsp )
** reflechir en particulier à la prod: quel est leur besoin

 
== scrap section

.how to display plantuml in asciidoc on github
[source]
----
:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/DBuret/myjournal/master/
image::{gitplant}/test.puml[test]
----

=== plantum deployment diag

image::{gitplant}/deploy.puml[objets dans un diagramme de deploiement]
