= notes de lecture
:author: David Buret
:source-highlighter: pygments
:pygments-style: emacs
:icons: font
:sectnums:
:toclevels: 4
:toc:
:imagesdir: images/
:toc-title: Sommaire


== A creuser
 
cette section est in pense bete des sujets a creuser
 
* uml: revenir aux sources, lire la doc officielle de http://www.omg.org
* iso 42010
 

== en cours
 
.Management
* the toyota way (management)
* demming
 
.Architecture
* uml'2.0'in action
* Software Systems Architecture: 
Working with Stakeholders Using Viewpoints and Perspectives (
Nick Rozanski,
Eoin Woods)
 
== Software Systems Architecture: Working with Stakeholders Using Viewpoints and Perspectives 

.Notes de lectures
* le triangle qualite,cout,time to market est a reutiliser
* il faut devenir expert un diagrammes de deploiement, et adapterr le concept au plateformes cloud & conteneurs
* il faut formaliser quels sont mes stakeholders, et definir les viewpoints et perspectives adaptés

 
== scrap section

=== github et plantuml

way is significantly different and simpler than the answer above; it uses the PlantUML proxy service:

http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt

The GitHub asciidoc for this would be:



image::http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/dburet/myjounal/test.puml



=== plantum deployment diag

.objets dans un diagramme de deploiement
[plantuml]
----
actor actor
agent agent
artifact artifact
boundary boundary
card card
cloud cloud
component component
control control
database database
entity entity
file file
folder folder
frame frame
interface  interface
node node
package package
queue queue
stack stack
rectangle rectangle
storage storage
usecase usecase
----